# Install nodejs and npm
---
- name: Install node and npm
  hosts: webserver
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new Linux user
  hosts: webserver
  become: true
  become_user: root
  tasks:
    - name: Create Linux user
      user:
        name: yicheng
        comment: Admin user
        group: admin

- name: Deploy nodejs app
  hosts: webserver
  become: true
  become_user: yicheng
  tasks:
    - name: Unpack the nodejs file and copy to the remote server
      unarchive:
        src: "{{ playbook_dir }}/simple-nodejs-master/nodejs-app-1.0.0.tgz" # Local
        dest: /home/yicheng # Remote
    - name: Install dependencies from package.json with npm
      npm:
        path: /home/yicheng/package # Dir containing package.json
    - name: Start the application
      command: # command and shell modules are not idempotent, use conditionals to mitigate
        chdir: /home/yiheng/package/app
        cmd: node server.js
      async: 1000 # Timeout in seconds for the async task
      poll: 0 # Polling interval in seconds for the next task to start
    - name: Ensure the app is running
      shell: ps aux | grep node # shell module allows use of operators, env vars, etc.
      register: app_status # Store the output of the command in a variable
    - debug: msg={{app_status.stdout_lines}} # Use debug to print out the stdout